[package]
name = "actions-toolkit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "actions_toolkit.rs"

[dependencies]
wasm-bindgen = "0.2"

[workspace]
members = [
    # Multiline
    "packages/core",
    "packages/exec",
]
